### PR TITLE
Fix cfg80211_rtw_change_beacon on kernel 6.5

### PR DESCRIPTION
**Pull request by Jookia**

### CODE REVIEW

**Comment by lwfinger** [comment]
Merged. Thank You.

**Comment by prahal** [comment]
@Jookia I opened bug #44  since your push request broke the build at least for 6.6 and above.
The signature for change_beacon https://elixir.bootlin.com/linux/latest/source/include/net/cfg80211.h#L4452 has not changed, why this push request?

**Comment by Jookia** [comment]
Oh, oops. This might be a fix for 6.7.

**Comment by Jookia** [comment]
I will track down the history for this change and do a new PR to fix.

**Pull request merged**
